pipeline {

    agent any

    environment {
        DOCKERHUB_USER  = 'kevinmbassi'
        IMAGE_NAME      = 'flask-app-mbassi-elessa'
        IMAGE_TAG       = 'latest'
        GITHUB_REPO     = 'https://github.com/Rodolphe-10/flask-app-mbassi-elessa.git'
        DOCKERHUB_CREDS = credentials('dockerhub-credentials')
    }

    stages {

        stage('Clonage') {
            steps {
                echo '=== Clonage du depot GitHub ==='
                git branch: 'main', url: 'https://github.com/Rodolphe-10/flask-app-mbassi-elessa.git'
                echo '=== Fichiers recuperes ==='
                sh 'ls -la'
            }
        }

        stage('Image') {
            steps {
                echo '=== Construction de l image Docker ==='
                sh 'docker build -t kevinmbassi/flask-app-mbassi-elessa:latest .'
                echo '=== Image construite ==='
                sh 'docker images | grep flask-app-mbassi-elessa'
            }
        }

        stage('Publication') {
            steps {
                echo '=== Publication sur DockerHub ==='
                sh '''
                    echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin
                    docker push kevinmbassi/flask-app-mbassi-elessa:latest
                    docker logout
                '''
                echo '=== Image publiee sur DockerHub ==='
            }
        }
    }

    post {
        success {
            echo 'Pipeline execute avec succes !'
        }
        failure {
            echo 'Echec du pipeline — verifiez les logs'
        }
        always {
            sh 'docker rmi kevinmbassi/flask-app-mbassi-elessa:latest || true'
        }
    }
}
